apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-green
  namespace: ${k8s_ns}
  labels:
    app: ${artifactId}-green
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: ${appPort}
      targetPort: ${appPort}
      protocol: TCP
      name: restful
  selector:
    app: ${artifactId}-green

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${artifactId}-green
  namespace: ${k8s_ns}
spec:
  replicas: ${replicas}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ${artifactId}-green
  template:
    metadata:
      labels:
        name: ${artifactId}-green
        app: ${artifactId}-green
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - suzhou
                      - wuxi
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ${artifactId}-green
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ${artifactId}-green
      tolerations:
        - key: node.pool.kubernetes.io
          operator: Equal
          value: p15f1
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: safebox-logs
          hostPath:
            path: /apps/logs/bcsec/safebox/normal/${artifactId}-green
      containers:
        - name: ${artifactId}-green
          image: ${docker_prefix}/${artifactId}-green:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: ${appPort}
              path: /api/web/${product}/${module}/common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: ${appPort}
              path: /api/web/${product}/${module}/common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '0.3'
              memory: 800Mi
            limits:
              cpu: '0.3'
              memory: 1Gi
          volumeMounts:
            - mountPath: /apps/logs/bcsec/safebox
              name: safebox-logs
          ports:
            - containerPort: ${appPort}
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

