apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-${gray}
  namespace: ${k8s_ns}
  labels:
    app: ${artifactId}-${gray}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: ${appPort}
      targetPort: ${appPort}
      protocol: TCP
      name: restful
  selector:
    app: ${artifactId}-${gray}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${artifactId}-${gray}
  namespace: ${k8s_ns}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ${artifactId}-${gray}
  template:
    metadata:
      labels:
        name: ${artifactId}-${gray}
        app: ${artifactId}-${gray}
    spec:
      restartPolicy: Always
      volumes:
        - name: safebox-logs
          hostPath:
            path: /apps/logs/bcsec/safebox/normal/${artifactId}-${gray}
      containers:
        - name: ${artifactId}-${gray}
          image: ${docker_prefix}/${artifactId}:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: ${appPort}
              path: /api/web/${product}/${module}/common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: ${appPort}
              path: /api/web/${product}/${module}/common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '0.3'
              memory: 800Mi
            limits:
              cpu: '0.3'
              memory: 1Gi
          volumeMounts:
            - mountPath: /apps/logs/bcsec/safebox
              name: safebox-logs
          ports:
            - containerPort: ${appPort}
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

