apiVersion: v1
kind: Service
metadata:
  name: basic-gray
  namespace: ${k8s_ns}
  labels:
    app: basic-gray
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: restful
  selector:
    app: basic-gray

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: basic-gray-deployment
  namespace: ${k8s_ns}
spec:
  replicas: ${replicas}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: basic-gray
  template:
    metadata:
      labels:
        name: basic-gray
        app: basic-gray
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - suzhou
                      - wuxi
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - basic-gray
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: basic-gray
      tolerations:
        - key: node.pool.kubernetes.io
          operator: Equal
          value: p15f1
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: app-logs
          hostPath:
            path: /tmp/apps/basic-gray/logs
      containers:
        - name: basic-gray-deployment
          image: ${docker_prefix}/basic-gray:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /basic/common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: 8080
              path: /basic/common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '1'
              memory: 1Gi
            limits:
              cpu: '1'
              memory: 1.5Gi
          volumeMounts:
            - mountPath: /opt/app/basic/logs
              name: app-logs
          ports:
            - containerPort: 8080
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

