apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}
  namespace: ${k8s_ns}
  labels:
    app: ${artifactId}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: ${appPort}
      targetPort: ${appPort}
      protocol: TCP
      name: restful
  selector:
    app: ${artifactId}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${artifactId}-deployment
  namespace: ${k8s_ns}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ${artifactId}
  template:
    metadata:
      labels:
        name: ${artifactId}
        app: ${artifactId}
    spec:
      restartPolicy: Always
      volumes:
        - name: app-logs
          hostPath:
            path: /tmp/apps/${artifactId}/logs
      containers:
        - name: ${artifactId}
          image: ${docker_prefix}/${artifactId}:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: ${appPort}
              path: /${artifactId}/common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: ${appPort}
              path: /${artifactId}/common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '1'
              memory: 1Gi
            limits:
              cpu: '1'
              memory: 1.5Gi
          volumeMounts:
            - mountPath: /opt/app/${artifactId}/logs
              name: app-logs
          ports:
            - containerPort: ${appPort}
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

